### ISSUE TITLE
Auto Reload: Not working 

### ISSUE THREAD

**Issue by Daf57** [samytichadou/Auto_Reload_Blender_addon#36] opened 2024-10-20 14:40 UTC
Hello,

Blender 4.2.3LTS - I have Auto Reload installed from Extension.org. I have the settings a shown in attached image. 
With Blender open and the scene active - I am making changes in Substance Painter, exporting the textures then return to Blender to view updated textures. They do not auto update, even tho set to do so at 5 sec they remain unchanged for minutes - I have to use ALT+R in Shader Editor to get them to update. What am I doing wrong? 

![autoreload pg](https://github.com/user-attachments/assets/0c0b6efe-fd06-412f-8b1a-62f747fe8a15)

**Comment by Daf57** [comment] 2024-10-20 19:59
Seems to have started working. Not sure what the deal was but please disregard or delete.
Thanks

**Comment by rcstuber** [comment] 2024-11-01 21:09
I can confirm this issue. The add-on is not working for me on Mac M1. I tried uninstalling and reinstalling several times and restarted Blender – automatic refreshes are not happening. Only if I press the refresh icon in the AR menu bar, it reloads.

**Comment by samytichadou** [comment] 2024-12-13 16:30
> I can confirm this issue. The add-on is not working for me on Mac M1. I tried uninstalling and reinstalling several times and restarted Blender – automatic refreshes are not happening. Only if I press the refresh icon in the AR menu bar, it reloads.

Would you be able to test with last version ? v3.1.1 (you can upload from within blender preferences) and tell me if this is now working ? thanks

**Comment by rcstuber** [comment] 2024-12-13 19:30
I tested it with version 3.1.1 and Blender 4.2.3 LTS. Problem sadly still exists. Only reloads when manually pressing the refresh icons of the addon

**Comment by samytichadou** [comment] 2024-12-14 01:15
> I tested it with version 3.1.1 and Blender 4.2.3 LTS. Problem sadly still exists. Only reloads when manually pressing the refresh icons of the addon

thanks for testing, could you activate debug toggle (addon preferences) and tell me when you activate timer what is its console output ? thanks, sorry for the inconvenience !

**Comment by rcstuber** [comment] 2024-12-17 09:17
Oh boy – I think I missed the stopwatch button. It was turned off. It looks like it is disabled by default which I would not expect, when I activate such plugin. But in the end it's an RTFM issue, so sorry for causing you a headache.

**Comment by samytichadou** [comment] 2024-12-17 10:58
No problem, yes it could be clearer, I agree. I'll see to add some precisions in readme...
Glad it works for you, closing the issue.

**Closed by samytichadou** 2024-12-17 10:58 UTC
Labels: bug
