### ISSUE TITLE
Reload Error Popup Blender 4.2

### ISSUE THREAD

**Issue by MarkShand** [samytichadou/Auto_Reload_Blender_addon#37] opened 2024-11-02 04:18 UTC
If I click the reload button, this error is popping up, the image is not reloaded.

![image](https://github.com/user-attachments/assets/412e7af8-182e-440f-acfe-0b5827ac581d)

**Comment by samytichadou** [comment] 2024-11-02 23:48
thanks for reporting, can't reproduce for now, i would need some context :
- which os ?
- which blender version ?
- which image (or type if you can't share)
- did you try to isolate the faulty image in a new blend to reproduce the bug ?

Thanks, cheers

**Comment by samytichadou** [comment] 2024-12-03 11:13
closing for lack of details

**Closed by samytichadou** 2024-12-03 11:13 UTC
