### ISSUE TITLE
Auto Reload causes overlap in the top header

### ISSUE THREAD

**Issue by hokutonanto** [samytichadou/Auto_Reload_Blender_addon#17] opened 2021-12-02 01:52 UTC
Hi there,

First off, thanks for creating this handy add-on.
I'm having an issue when the add-on is activated: when open the file browser, an overlap occurs in the top header tow (see attached)

https://user-images.githubusercontent.com/23059969/144342943-1608e02f-f23d-4071-a6eb-17ddc09ce6e0.mp4

**Comment by samytichadou** [comment] 2021-12-05 17:05
Hey, i am unable to reproduce this issue with windows 10, blender 2.93. Are you sure this is related to autoreload ?
Except for appending a button here, the addon does not mess with the top header, which version of blender did you use ? do you have an error in the console or something ?

**Comment by hokutonanto** [comment] 2021-12-05 23:10
@samytichadou Are you trying on an HD display? I just noticed it doesn't happen on my second display, which is HD, though it happens on my primary UHD display.

**Comment by samytichadou** [comment] 2021-12-05 23:12
just tried on a fhd, i do not have a uhd one to test... It does not happen when auto reload is deactivated i presume ?

**Comment by hokutonanto** [comment] 2021-12-05 23:13
> just tried on a fhd, i do not have a uhd one to test... It does not happen when auto reload is deactivated i presume ?

By deactivated, you mean when is off? If so, yes, it doesn't happen.

**Comment by samytichadou** [comment] 2021-12-05 23:20
Ok, i guess this is a blender issue, giving autoreload header menu is just a menu prepended to this area. Pretty normal python coding, no fancy gpu_draw or anything. 
I guess for now you could try to deactivate this menu to confirm it is the cause of the bug
by commenting line 157 and 165 of gui.py file
(`bpy.types.TOPBAR_HT_upper_bar.prepend(file_menu_drawer` and `bpy.types.TOPBAR_HT_upper_bar.remove(file_menu_drawer`)
This should prevent this bug.
But I don't really have a workaround for it, except moving this menu somewhere else... I really don't know where this comes from for now sry !

**Comment by hokutonanto** [comment] 2021-12-05 23:25
Thanks @samytichadou commenting those two lines did the trick, the issue is gone.
Would the auto-reload keep working then? I guess, sort of, right? Considering now I can't access the options in the buttom...

**Comment by samytichadou** [comment] 2021-12-05 23:28
yes the addon itself is working but a few functions would not be accessible... You can maybe put functions of autoreload in your quick favorite menu for the time being ? 
I will try to make a dummy addon, when i have extra time, with only a top header label to see if this bug is reproducible, and maybe report it to blender foundation. 
Would it be ok to run it by you for testing on your uhd display ?

**Comment by hokutonanto** [comment] 2021-12-05 23:34
> [...] Would it be ok to run it by you for testing on your uhd display ?

Oh, absolutely. I'd be happy to test it if it can help to figure out the issue.

Thanks!

**Comment by samytichadou** [comment] 2021-12-06 23:19
Hey, [here it is](https://github.com/samytichadou/dummy_blender_addon/raw/main/dumdum.py) , a dummy addon named dumdum to add a label in the topbar header. You have to "save link as", and put this script in your addon folder (not a subfolder), then activate it to test.
Tell me if the bug is still here when autoreload is not enabled, and dumdum is.
Thank you for testing this out.

**Comment by hokutonanto** [comment] 2021-12-06 23:39
Thanks @samytichadou 

It seems to be working fine here. I've tried several operations that trigger the file browser, and so far the issue hasn't happened once.

**Comment by samytichadou** [comment] 2021-12-07 00:13
That's interesting... can't figure out the origin of this bug, [can you try this one](https://github.com/samytichadou/dummy_blender_addon/raw/main/dumdum.py) ? you have to uninstall dumdum first !
Thanks again !

**Comment by hokutonanto** [comment] 2021-12-07 00:31
Sure, I tried. This also seems to be working fine.

**Comment by samytichadou** [comment] 2021-12-07 00:39
OK, I'll try with properties and other ui things tomorrow, if you don't mind testing some more :)
Thanks for that and sorry for the inconvenience, still no clue so far...
Cheers

**Comment by hokutonanto** [comment] 2021-12-07 00:49
No problem at all, glad to be able to help!

**Comment by samytichadou** [comment] 2021-12-07 11:22
[Here is a new version](https://github.com/samytichadou/dummy_blender_addon/raw/main/dumdum.py) which mimicks the behavior of autoreload, can you try it with property toggled on and off ? maybe the icon in the header is the one causing this problem...
Thanks again !

**Comment by hokutonanto** [comment] 2021-12-07 21:06
Thanks, @samytichadou 
This is kind of working. When I click on the Prop icon, the issue occurs, but then once I resize the overlapping area back to normal, accessing the file browser doesn't cause the issue anymore. So, I guess a part from the initial glitch, this is mostly there.

**Comment by matteoscopel** [comment] 2022-01-26 09:30
Hello!

Just writing as I am also affected by this issue. When Blender opens a new window, the overlapping happens in the main window. Also, when with my cursor I overlay the Auto Reload menu, the menubar on the left flashes.

I am using Windows 11 with an Nvidia RTX 2060. I am using Blender 3.0 with the Optix backend.

Thank you for your great work on this useful addon!

**Comment by matteoscopel** [comment] 2022-01-31 07:57
Hello again! Since Blender 3.0.1, it seems the issue doesn't happen anymore. I think, but am not sure, that the issue was fixed with this commit: https://developer.blender.org/rB4cf4bb2664ebe145dac9715bbbfcc2b96f5ff175

**Comment by samytichadou** [comment] 2022-01-31 09:17
> Hello again! Since Blender 3.0.1, it seems the issue doesn't happen anymore. I think, but am not sure, that the issue was fixed with this commit: https://developer.blender.org/rB4cf4bb2664ebe145dac9715bbbfcc2b96f5ff175

Hey, thanks for the report, nice to hear, sorry for the delay, my hands are full right now at work... 
I won't close this issue until you and @hokutonanto does not confirm me that issue is gone for good with 3.1 version. 

Cheers

**Comment by hokutonanto** [comment] 2022-02-16 17:16
Apologies for the late reply. It seems the problem is indeed gone in the Blender 3.0.1.

**Comment by samytichadou** [comment] 2022-02-17 09:40
> Apologies for the late reply. It seems the problem is indeed gone in the Blender 3.0.1.

thanks for the follow up guys ! Closing this

**Closed by samytichadou** 2022-02-17 09:40 UTC
