### ISSUE TITLE
Keeps saying "missing images"

### ISSUE THREAD

**Issue by nielsotto** [samytichadou/Auto_Reload_Blender_addon#9] opened 2021-01-14 20:45 UTC
It keeps saying "missing images" in the panel, though I have loaded a bunch of images. What gives?

**Comment by samytichadou** [comment] 2021-01-28 01:11
duplicate of https://github.com/samytichadou/Auto_Reload-Blender_addon/issues/8

**Closed** 2021-01-28 01:15 UTC
Labels: duplicate
